---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-ipv8
spec:
  databases:
    login: login
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: '13'
  teamId: acid
  users:
    login: []
  volume:
    size: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: psql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psql
  selector:
    cluster-name: acid-ipv8
